"""added price column in event table

Revision ID: 8c61e9c9c5dc
Revises: a0d97bd7af1a
Create Date: 2025-06-03 15:39:02.402133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c61e9c9c5dc'
down_revision: Union[str, None] = 'a0d97bd7af1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('payment_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('login_history')
    op.drop_table('payment_info')
    op.drop_table('users')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_gov_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tikets_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', mysql.DATETIME(), nullable=False),
    sa.Column('ended_at', mysql.DATETIME(), nullable=False),
    sa.Column('venue_address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_fullybooked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('vendors_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vendors_id'], ['vendors.id'], name='events_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_table('customers',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('gov_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_index(op.f('ix_customers_gov_id'), 'customers', ['gov_id'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_table('tickets',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('booking_id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('event_id', mysql.VARCHAR(length=12), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('tickets_ibfk_1')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('tickets_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vendors',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('support_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'user'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payment_info',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('method', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('bank_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('card_number', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tax', mysql.FLOAT(), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'CANCELLED'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('login_history',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('logout_date', mysql.DATETIME(), nullable=True),
    sa.Column('device_id', mysql.VARCHAR(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('login_history_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bookings',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('customer_id', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('payment_status', mysql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'CANCELLED'), nullable=False),
    sa.Column('event_id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('payment_id', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('bookings_ibfk_1')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('bookings_ibfk_2')),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_info.id'], name=op.f('bookings_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('payment_id'), 'bookings', ['payment_id'], unique=True)
    # ### end Alembic commands ###
