"""payment_method, payment_info revisoin 3

Revision ID: e62b7aca3b84
Revises: 6659f0f17082
Create Date: 2025-06-07 06:25:47.308810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e62b7aca3b84'
down_revision: Union[str, None] = '6659f0f17082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('payment_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_payment_method_id'), table_name='payment_method')
    op.drop_table('payment_method')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_gov_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_payment_info_id'), table_name='payment_info')
    op.drop_table('payment_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_info',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'CANCELLED'), nullable=False),
    sa.Column('tax', mysql.FLOAT(), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('payment_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('payment_method_id', mysql.VARCHAR(length=12), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], name='payment_info_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payment_info_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_payment_info_id'), 'payment_info', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('booking_id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('event_id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=12), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('tickets_ibfk_1')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('tickets_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tickets_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customers',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('gov_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='customers_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_gov_id'), 'customers', ['gov_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_table('events',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tikets_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', mysql.DATETIME(), nullable=False),
    sa.Column('ended_at', mysql.DATETIME(), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('venue_address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_fullybooked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'user', 'organizer'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('payment_method',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('card_number', mysql.VARCHAR(length=19), nullable=True),
    sa.Column('bank_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('card_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('expired_month', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expired_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('placeholder_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=12), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payment_method_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_payment_method_id'), 'payment_method', ['id'], unique=False)
    op.create_table('login_history',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('logout_date', mysql.DATETIME(), nullable=True),
    sa.Column('device_id', mysql.VARCHAR(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('login_history_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bookings',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('customer_id', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('payment_status', mysql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'CANCELLED'), nullable=False),
    sa.Column('event_id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('payment_id', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=12), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('bookings_ibfk_1')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('bookings_ibfk_2')),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_info.id'], name=op.f('bookings_ibfk_3')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookings_ibfk_4')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('payment_id'), 'bookings', ['payment_id'], unique=True)
    # ### end Alembic commands ###
